name: create environment

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: number

jobs:
  build:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: self-hosted
    environment:
      name: pr-${{ github.event.pull_request.number || github.event.inputs.pr_number }}
      url: https://eduid-invite-proxy-pr-${{ github.event.pull_request.number || github.event.inputs.pr_number }}.datanose.nl/

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Build and deploy
        env:
          PR_NUMBER: ${{ github.event.pull_request.number || github.event.inputs.pr_number }}
          UPDATER_SECRET: ${{ secrets.UPDATER_SECRET_DN }}
        run: |
          set -euxo pipefail
          TAG="pr-${PR_NUMBER}"
          docker build -f UvA.SecureEduIdInviteProxy/Dockerfile -t "datanosecr.azurecr.io/eduid-invite-proxy:${TAG}" .
          docker push "datanosecr.azurecr.io/eduid-invite-proxy:${TAG}"
          VERSION=$(date "+1.0.%Y%m%d%H%M%S")
          helm package --version "${VERSION}" --app-version "${VERSION}" charts/eduid-invite-proxy-pr
          helm push "eduid-invite-proxy-pr-${VERSION}.tgz" oci://datanosecr.azurecr.io/helm
          curl --fail --no-progress-meter "https://eduid-invite-proxy-tst.datanose.nl/gitops-updater?name=eduid-invite-proxy-pr&secret=${UPDATER_SECRET}&version=${VERSION}&id=${PR_NUMBER}"
